"""empty message

Revision ID: 63c42cc92d9a
Revises: 
Create Date: 2023-03-23 14:37:02.032827

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '63c42cc92d9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_Gender_pay',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('DiffMeanHourlyPercent', sa.String(length=128), nullable=False),
                    sa.Column('DiffMedianHourlyPercent', sa.String(length=128), nullable=False),
                    sa.Column('DiffMeanBonusPercent', sa.String(length=128), nullable=False),
                    sa.Column('DiffMedianBonusPercent', sa.String(length=128), nullable=False),
                    sa.Column('MaleBonusPercent', sa.String(length=128), nullable=False),
                    sa.Column('FemaleBonusPercent', sa.String(length=128), nullable=False),
                    sa.Column('MaleLowerQuartile', sa.String(length=128), nullable=False),
                    sa.Column('FemaleLowerQuartile', sa.String(length=128), nullable=False),
                    sa.Column('MaleLowerMiddleQuartile', sa.String(length=128), nullable=False),
                    sa.Column('FemaleLowerMiddleQuartile', sa.String(length=128), nullable=False),
                    sa.Column('MaleUpperMiddleQuartile', sa.String(length=128), nullable=False),
                    sa.Column('FemaleUpperMiddleQuartile', sa.String(length=128), nullable=False),
                    sa.Column('MaleTopQuartile', sa.String(length=128), nullable=False),
                    sa.Column('FemaleTopQuartile', sa.String(length=128), nullable=False),
                    sa.Column('EmployerSize', sa.String(length=128), nullable=False),
                    sa.Column('Region', sa.String(length=128), nullable=False),
                    sa.Column('Industry', sa.String(length=128), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_Gender_pay')
    # ### end Alembic commands ###
